<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BlogService\Blog.Contracts\Blog.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\MessageBus\MessageBus.csproj" />
    <ProjectReference Include="..\..\GetewayService\AspireTest\AspireTest.ServiceDefaults\AspireTest.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Search.Domain\Search.Domain.csproj" />
    <ProjectReference Include="..\Search.Persistence\Search.Persistence.csproj" />
    <ProjectReference Include="..\Search.Service\Search.Service.csproj" />
  </ItemGroup>

</Project>
