// <auto-generated />
using System;
using Conference.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conference.Persistence.Migrations
{
    [DbContext(typeof(ConferenceDbContext))]
    partial class ConferenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Conference")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceParticipant", b =>
                {
                    b.Property<Guid>("ConferenceRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ConferenceRoomId", "SessionId");

                    b.HasIndex("ConferenceRoomId", "UserId")
                        .IsUnique();

                    b.ToTable("ConferenceParticipants", "Conference");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceInvitation", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid>("ActorUserId").HasColumnType("uuid");
                    b.Property<Guid>("ConferenceId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("RecipientUserId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("ConferenceId", "RecipientUserId").IsUnique();
                    b.ToTable("ConferenceInvitations", "Conference");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceOutboxMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<Guid?>("CorrelationId").HasColumnType("uuid");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ErrorMessage").HasColumnType("text");
                    b.Property<string>("EventData").IsRequired().HasColumnType("text");
                    b.Property<string>("EventType").IsRequired().HasColumnType("text");
                    b.Property<int>("RetryCount").HasColumnType("integer");
                    b.Property<int>("State").HasColumnType("integer");
                    b.HasKey("Id");
                    b.ToTable("OutboxMessages", "Conference");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ConferenceRooms", "Conference");
                });

            modelBuilder.Entity("Conference.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConferenceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceId");

                    b.ToTable("Messages", "Conference");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceParticipant", b =>
                {
                    b.HasOne("Conference.Domain.Entities.ConferenceRoom", "ConferenceRoom")
                        .WithMany("Participants")
                        .HasForeignKey("ConferenceRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceRoom");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceInvitation", b =>
                {
                    b.HasOne("Conference.Domain.Entities.ConferenceRoom", null)
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conference.Domain.Entities.Message", b =>
                {
                    b.HasOne("Conference.Domain.Entities.ConferenceRoom", "Room")
                        .WithMany()
                        .HasForeignKey("ConferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Conference.Domain.Entities.ConferenceRoom", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
