version: '3.4'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      URLS: "[ { url: \"/auth/swagger/v1/swagger.json\", name: \"Authorization\" }, { url: \"/profile/swagger/v1/swagger.json\", name: \"Profile\" },{ url: \"/videos/swagger/v1/swagger.json\", name: \"Video\" }]"
  nginx:
    image: nginx:alpine
    ports:
        - ${NGINX_PORT-7892}:80
    volumes:
      - ./nginx/nginx.local-debug.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-frontend-dev.conf:/etc/nginx/nginx-frontend.conf:ro
  # profile-app:
  #   build:
  #       context: ./
  #       dockerfile: ProfileApplication/Dockerfile
  #   ports:
  #     - "5069:8080" 
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  minio:
    container_name: fileStorage
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
  database:
    container_name: postgresDb
    image: postgres:16.6
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=person_blog
        - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
        - ../db:/var/lib/postgresql/data
  rabbitMq:
    image: rabbitmq:3.13-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ../rabbitMq:/var/lib/rabbitmq
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USER=admin
      - REDIS_USER_PASSWORD=admin
    volumes:
    - ../redisdata:/data
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight_container
    ports:
      - "5540:5540"
    volumes:
      - ../redis_insight_data:/db
    depends_on:
      - redis
  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false