version: '3.4'

services: 
  nginx:
    image: nginx:alpine
    ports:
        - ${NGINX_PORT-7892}:80
    volumes:
      - ./nginx/nginx.local-debug.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-frontend-dev.conf:/etc/nginx/nginx-frontend.conf:ro
    networks:
      - backend      
  minio:
    container_name: fileStorage
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - backend
  database:
    container_name: postgresDb
    image: postgres:16.6
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=person_blog
        - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
        - ../db:/var/lib/postgresql/data
    networks:
      - backend        
  rabbitMq:
    image: rabbitmq:3.13-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ../rabbitMq:/var/lib/rabbitmq
    networks:
      - backend      
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USER=admin
      - REDIS_USER_PASSWORD=admin
    volumes:
    - ../redisdata:/data
    networks:
      - backend    
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight_container
    ports:
      - "5540:5540"
    volumes:
      - ../redis_insight_data:/db
    depends_on:
      - redis
    networks:
      - backend      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - ../es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend      

  tokenizer-app:
    build:
      context: .
      dockerfile: TokenizerService/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./TokenizerService:/app
    networks:
      - backend      
  #auth-app:
  #  container_name: auth-app
  #  depends_on: [rabbitMq]
  #  build:
  #      context: ./
  #      dockerfile: ./AuthService/AuthenticationApplication/Dockerfile
  #  ports:
  #    - "5179:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  networks:
  #    - backend      
  #blog-app:
  #  container_name: blog-app
  #  depends_on: [rabbitMq]
  #  build:
  #      context: ./
  #      dockerfile: ./BlogService/Blog.API/Dockerfile
  #  ports:
  #    - "5069:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  networks:
  #    - backend
  #videoprocess-app:
  #  depends_on: [blog-app]
  #  container_name: videoprocess-app
  #  build:
  #      context: ./
  #      dockerfile: ./BlogService/VideoProcessing.Cli/Dockerfile
  #  ports:
  #    - "5281:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./BlogService/VideoProcessing.Cli/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
  #videoview-app:
  #  container_name: videoview-app
  #  build:
  #      context: ./
  #      dockerfile: ./VideoService/VideoView.Application/Dockerfile
  #  ports:
  #    - "5165:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./VideoService/VideoView.Application/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
  #videoreacting-app:
  #  container_name: videoreacting-app
  #  build:
  #      context: ./
  #      dockerfile: ./ViewReactingService/VideoReacting.API/Dockerfile
  #  ports:
  #    - "5153:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./ViewReactingService/VideoReacting.API/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
  #searchservice-app:
  #  container_name: searchservice-app
  #  build:
  #      context: ./
  #      dockerfile: ./SearchService/SearchService.Application/Dockerfile
  #  ports:
  #    - "5250:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./SearchService/SearchService.Application/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend      
  #recommendation-app:
  #  container_name: recommendation-app
  #  build:
  #      context: ./
  #      dockerfile: ./RecommendationService/Recommendation.Application/Dockerfile
  #  ports:
  #    - "5209:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./RecommendationService/Recommendation.Application/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
  #commentservice-app:
  #  container_name: commentservice-app
  #  build:
  #      context: ./
  #      dockerfile: ./CommentService/Comments.API/Dockerfile
  #  ports:
  #    - "5124:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./CommentService/Comments.API/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
  #conferenceservice-app:
  #  container_name: conferenceservice-app
  #  build:
  #      context: ./
  #      dockerfile: ./ConferenceService/Conference.API/Dockerfile
  #  ports:
  #    - "5193:8080" 
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Realese
  #  volumes:
  #    - ./ConferenceService/Conference.API/appsettings.json:/app/appsettings.json
  #  networks:
  #    - backend
networks:
  backend:
    driver: bridge