version: '3.4'

services: 
  nginx:
    image: nginx:alpine
    ports:
        - ${NGINX_PORT-7892}:80
    volumes:
      - ./nginx/nginx.local-debug.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-frontend-dev.conf:/etc/nginx/nginx-frontend.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
    networks:
      - backend      
  minio:
    container_name: fileStorage
    image: minio/minio
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      - backend
  database:
    container_name: postgresDb11
    image: postgres:16.6
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=person_blog
        - POSTGRES_PASSWORD=1
    ports:
      - "5432:5432"
    volumes:
        - ../db:/var/lib/postgresql/data
    networks:
      - backend        
  rabbitMq:
    image: rabbitmq:3.13-management
    container_name: rabbitMq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ../rabbitMq:/var/lib/rabbitmq
    networks:
      - backend      
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=admin
      - REDIS_USER=admin
      - REDIS_USER_PASSWORD=admin
    volumes:
    - ../redisdata:/data
    networks:
      - backend    
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight_container
    ports:
      - "5540:5540"
    volumes:
      - ../redis_insight_data:/db
    # depends_on:
      # - redis
    networks:
      - backend      

networks:
  backend: