version: '3.4'

networks:
  backend:
    external: true

services: 
  auth-app:
   container_name: auth-app
   image: auth-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./AuthService/AuthenticationApplication/Dockerfile
   ports:
     - "5179:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/auth-app/appsettings.json:/app/appsettings.json
   networks:
     - backend      
  blog-app:
   container_name: blog-app
   image: blog-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./BlogService/Blog.API/Dockerfile
   ports:
     - "5069:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/blog-app/appsettings.json:/app/appsettings.json
   networks:
     - backend
  videoprocess-app:
   depends_on: [blog-app]
   container_name: videoprocess-app
   image: videoprocess-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./BlogService/VideoProcessing.Cli/Dockerfile
   ports:
     - "5281:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/videoprocess-app/appsettings.json:/app/appsettings.json
   networks:
     - backend
  playlist-app:
   container_name: playlist-app
   image: playlist-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./PlayListService/PlayListService.API/Dockerfile
   ports:
     - "5147:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/playlist-app/appsettings.json:/app/appsettings.json
   networks:
     - backend
  gateway-app:
   container_name: gateway-app
   image: gateway-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./GetewayService/Gateway.API/Dockerfile
   ports:
     - "5165:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/gateway-app/appsettings.json:/app/appsettings.json
   networks:
     - backend
  profile-app:
   container_name: profile-app
   image: profile-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./ProfileService/Profile.API/Dockerfile
   ports:
     - "5153:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/profile-app/appsettings.json:/app/appsettings.json
   networks:
     - backend
  recommendation-app:
   container_name: recommendation-app
   image: recommendation-app:latest
   user: "root"
   build:
       context: .
       dockerfile: ./RecommendationService/Recommendation.Application/Dockerfile
   ports:
     - "5209:8080" 
   environment:
     - ASPNETCORE_ENVIRONMENT=Release
   volumes:
     - ./configs/recommendation-app/appsettings.json:/app/appsettings.json
   networks:
     - backend