<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>5a4dc046-4ef2-4178-a0e2-00fff0b42fc9</UserSecretsId>
        <DockerfileContext>..\..</DockerfileContext>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\AuthService\Authentication.Contract\Authentication.Contract.csproj" />
      <ProjectReference Include="..\..\Common\FileStorage.Service\FileStorage.Service.csproj" />
      <ProjectReference Include="..\..\Common\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\..\Common\MessageBus.Shared\MessageBus.Shared.csproj" />
      <ProjectReference Include="..\..\Common\MessageBus\MessageBus.csproj" />
      <ProjectReference Include="..\..\GetewayService\AspireTest\AspireTest.ServiceDefaults\AspireTest.ServiceDefaults.csproj" />
      <ProjectReference Include="..\Blog.Contracts\Blog.Contracts.csproj" />
      <ProjectReference Include="..\Blog.Service\Blog.Service.csproj" />
      <ProjectReference Include="..\MediaProcessing.Contract\MediaProcessing.Contract.csproj" />
    </ItemGroup>

</Project>
