        
location /auth {
    proxy_pass http://host.docker.internal:5179/auth/;
}

location /profile {
    proxy_pass http://host.docker.internal:5069/profile/;
}

location /videos {
    proxy_pass http://host.docker.internal:5165/video/;
}

location / {
    root /usr/share/nginx/html;
    index index.html;
    
    try_files $uri $uri/ /index.html;
    
    location ~* \.(js|css|png|jpg|svg|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }
    
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}