        
location /auth {
    proxy_pass http://host.docker.internal:5179/auth/;
}

location /profile {
    proxy_pass http://host.docker.internal:5069/profile/;
}

location /videos {
    proxy_pass http://host.docker.internal:5165/video/;
}