// <auto-generated />
using System;
using Authentication.Peristence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Authentication.Peristence.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    partial class AuthenticationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Authentication")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Authentication.Domain.Entities.AppProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsDeleted")
                        .IsUnique();

                    b.ToTable("Profiles", "Authentication");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastAuthenticate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppUsers", "Authentication");

                    b.HasData(
                        new
                        {
                            Id = new Guid("09f3c24e-6e70-48ea-a5c5-60727af95d1e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 26, 9, 32, 13, 701, DateTimeKind.Unspecified).AddTicks(3537), new TimeSpan(0, 0, 0, 0, 0)),
                            LastAuthenticate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Login = "admin",
                            Password = "VacCRVsNifQ=;+M5kOYZEqn/MHZuMwpRUdX1OY9zTfS5sp31hUS+rFMw="
                        });
                });

            modelBuilder.Entity("Authentication.Domain.Entities.AppUserRole", b =>
                {
                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("AppUserId", "UserRoleId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("AppUserRoles", "Authentication");

                    b.HasData(
                        new
                        {
                            AppUserId = new Guid("09f3c24e-6e70-48ea-a5c5-60727af95d1e"),
                            UserRoleId = new Guid("d95ca3d6-0f63-4b48-a54f-1202f3d6bf2c")
                        });
                });

            modelBuilder.Entity("Authentication.Domain.Entities.AuthEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AuthEvents", "Authentication");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId", "RedirectUri")
                        .IsUnique();

                    b.ToTable("Clients", "Authentication");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Tokens", "Authentication");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.UserContext", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ContextId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ContextType", "ContextId");

                    b.ToTable("UserContexts", "Authentication");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles", "Authentication");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57a2b99b-b6ee-4c98-a1f0-b18fe96dae60"),
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("accbc12f-6ff1-4343-a26f-13b99e64abb6"),
                            Name = "superadmin"
                        },
                        new
                        {
                            Id = new Guid("d95ca3d6-0f63-4b48-a54f-1202f3d6bf2c"),
                            Name = "user"
                        },
                        new
                        {
                            Id = new Guid("c2ff298c-dd14-436c-a28b-e2036866ef41"),
                            Name = "blogger"
                        },
                        new
                        {
                            Id = new Guid("72c4bbed-5375-47fc-864f-1490ca82aced"),
                            Name = "artist"
                        });
                });

            modelBuilder.Entity("Authentication.Domain.Entities.AppUserRole", b =>
                {
                    b.HasOne("Authentication.Domain.Entities.AppUser", "AppUser")
                        .WithMany("AppUserRoles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Authentication.Domain.Entities.UserRole", "UserRole")
                        .WithMany("AppUserRole")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.Token", b =>
                {
                    b.HasOne("Authentication.Domain.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.UserContext", b =>
                {
                    b.HasOne("Authentication.Domain.Entities.AppUser", "AppUser")
                        .WithMany("UserContexts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("AppUserRoles");

                    b.Navigation("UserContexts");
                });

            modelBuilder.Entity("Authentication.Domain.Entities.UserRole", b =>
                {
                    b.Navigation("AppUserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
