<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<WarningsAsErrors>Nullable</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AuthService\Authentication.Contract\Authentication.Contract.csproj" />
    <ProjectReference Include="..\..\Common\FileStorage.Service\FileStorage.Service.csproj" />
    <ProjectReference Include="..\..\Common\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\..\GetewayService\AspireTest\AspireTest.ServiceDefaults\AspireTest.ServiceDefaults.csproj" />
    <ProjectReference Include="..\PlayListService.Persistence\PlayListService.Persistence.csproj" />
    <ProjectReference Include="..\PlayListService.Services\PlayListService.Services.csproj" />
  </ItemGroup>

</Project>
