// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayListService.Persistence;

#nullable disable

namespace PlayListService.Persistence.Migrations
{
    [DbContext(typeof(PlayListDbContext))]
    partial class PlayListDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("PlayList")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ThumbnailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("PlayLists", "PlayList");
                });

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayListFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PlaylistId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId")
                        .IsUnique();

                    b.ToTable("PlayListFile", "PlayList");
                });

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayListItem", b =>
                {
                    b.Property<Guid>("PlayListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("PlayListId", "PostId");

                    b.ToTable("PlayListItems", "PlayList");
                });

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayListFile", b =>
                {
                    b.HasOne("PlayListService.Domain.Entities.PlayList", "PlayList")
                        .WithOne("ThumbnailFile")
                        .HasForeignKey("PlayListService.Domain.Entities.PlayListFile", "PlaylistId");

                    b.Navigation("PlayList");
                });

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayListItem", b =>
                {
                    b.HasOne("PlayListService.Domain.Entities.PlayList", null)
                        .WithMany("PlayListItems")
                        .HasForeignKey("PlayListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayListService.Domain.Entities.PlayList", b =>
                {
                    b.Navigation("PlayListItems");

                    b.Navigation("ThumbnailFile");
                });
#pragma warning restore 612, 618
        }
    }
}
