// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VideoReacting.Persistence;

#nullable disable

namespace VideoReacting.Persistence.Migrations
{
    [DbContext(typeof(ViewReactingDbContext))]
    partial class ViewReactingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("VideoReacting")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ViewReacting.Domain.Entities.UserPostView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleteWatch")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("WatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WatchedTime")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("UserPostViews", "VideoReacting");
                });
#pragma warning restore 612, 618
        }
    }
}
