spring.application.name=adminPanel
spring.datasource.url=jdbc:postgresql://localhost:5432/person_blog
spring.datasource.username=postgres
spring.datasource.password=1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema="AdminPanel"
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

spring.thymeleaf.prefix=classpath:/templates/
spring.resources.static-locations=classpath:/templates/

blog.url = http://localhost:7892
blog.token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBhNDAyY2ZlLTM0NDQtNDJjOC1iMzNhLTgyYmY3MGIyYjM0OCIsInJvbGVJZCI6ImQ5NWNhM2Q2LTBmNjMtNGI0OC1hNTRmLTEyMDJmM2Q2YmYyYyIsImxvZ2luIjoiYWRtaW4iLCJ1c2VySWQiOiJkZmY5YmZmMi0zYTAzLTQwY2ItYTFiZC0xMzBlMmViNzk3NDMiLCJ0eXBlIjoiYWNjZXNzIiwiYmxvZ0lkIjoiMTBmMTNmZTMtYzgyZS00MGM5LThkZmEtMjU0YWM1ODEwNjc3IiwiZXhwaXJlQXQiOiIzMS4wOC4yMDI1IDc6MTA6MTYgKzAwOjAwIiwibmFtZSI6ImFkbWluIiwiZXhwIjoxNzU2NjI0MjE2LCJpc3MiOiJNeUF1dGhTZXJ2ZXIiLCJhdWQiOiJNeUF1dGhDbGllbnQifQ.VZn9OWOx42MCUV6d8wUfwxo_m6M9R712LNtIVgr4oyo