// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recommendation.Persistence;

#nullable disable

namespace Recommendation.Persistence.Migrations
{
    [DbContext(typeof(RecommendationDbContext))]
    partial class RecommendationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Recommendation")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recommendation.Domain.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAt", "ReceivedAt");

                    b.ToTable("InboxMessages", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.PostCategory", b =>
                {
                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("PostId", "CategoryId");

                    b.HasIndex("CategoryId", "PostId");

                    b.ToTable("PostCategories", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.PostSnapshot", b =>
                {
                    b.Property<Guid>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("integer");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PaymentSubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PreviewObjectName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProcessState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("SourceVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("PostId");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("BlogId", "CreatedAt");

                    b.HasIndex("Visibility", "ProcessState", "IsDeleted", "IsBanned");

                    b.ToTable("PostSnapshots", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.RecommendationImpression", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AnonymousSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CandidateSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ShownAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RequestId", "PostId");

                    b.HasIndex("AnonymousSessionId", "ShownAt");

                    b.HasIndex("PostId", "ShownAt");

                    b.HasIndex("UserId", "ShownAt");

                    b.ToTable("RecommendationImpressions", "Recommendation", t =>
                        {
                            t.HasCheckConstraint("CK_RecommendationImpressions_Subject", "(\"UserId\" IS NOT NULL AND \"AnonymousSessionId\" IS NULL) OR (\"UserId\" IS NULL AND \"AnonymousSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.UserBlogAffinity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BlogId");

                    b.HasIndex("UserId", "Score");

                    b.ToTable("UserBlogAffinities", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.UserCategoryAffinity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("UserId", "Score");

                    b.ToTable("UserCategoryAffinities", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.UserInteraction", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnonymousSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("PreviousReaction")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Reaction")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<double?>("WatchRatio")
                        .HasColumnType("double precision");

                    b.Property<double?>("WatchedSeconds")
                        .HasColumnType("double precision");

                    b.HasKey("EventId");

                    b.HasIndex("AnonymousSessionId", "OccurredAt");

                    b.HasIndex("PostId", "OccurredAt");

                    b.HasIndex("UserId", "OccurredAt");

                    b.ToTable("UserInteractions", "Recommendation", t =>
                        {
                            t.HasCheckConstraint("CK_UserInteractions_Subject", "(\"UserId\" IS NOT NULL AND \"AnonymousSessionId\" IS NULL) OR (\"UserId\" IS NULL AND \"AnonymousSessionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlogId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BlogId");

                    b.HasIndex("BlogId", "UserId");

                    b.ToTable("UserSubscriptions", "Recommendation");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.PostCategory", b =>
                {
                    b.HasOne("Recommendation.Domain.Entities.PostSnapshot", "Post")
                        .WithMany("Categories")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Recommendation.Domain.Entities.PostSnapshot", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
