// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Music.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Music.Persistence.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20250827095851_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Music")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Music.Domain.Entities.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeleteDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Artists", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.ArtistTrackLink", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.ToTable("ArtistTrackLinks", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genre", "Music");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f2778a49-d7bf-4681-902f-dbfcf5ae2a22"),
                            Name = "Альтернативный рок"
                        },
                        new
                        {
                            Id = new Guid("1e66ef2d-dc44-4a0e-94e4-936865bcd293"),
                            Name = "Альтернативный хип-хоп"
                        },
                        new
                        {
                            Id = new Guid("1d3caf62-dd89-4a1d-9b59-5390b59083c8"),
                            Name = "Академическая музыка"
                        },
                        new
                        {
                            Id = new Guid("dd1c1063-a144-4efd-824b-b9549ad31171"),
                            Name = "Африканская музыка"
                        },
                        new
                        {
                            Id = new Guid("1a0e3094-6407-4b9e-af9f-95e40128a2f3"),
                            Name = "Бардовская песня"
                        },
                        new
                        {
                            Id = new Guid("c850ac27-166e-4b06-a7ae-d9798c9251ef"),
                            Name = "Битмейкерская"
                        },
                        new
                        {
                            Id = new Guid("da0c444c-6af4-4dc1-a822-3fa818159f8f"),
                            Name = "Блэк-метал"
                        },
                        new
                        {
                            Id = new Guid("86e438cf-3974-4b13-b298-f9f67242b40f"),
                            Name = "Блюз"
                        },
                        new
                        {
                            Id = new Guid("68d95226-3d27-49a9-abe8-7843a4cf047d"),
                            Name = "Военная песня"
                        },
                        new
                        {
                            Id = new Guid("e94c084c-5f48-4c55-8c17-469b3a6804ec"),
                            Name = "Восточная музыка"
                        },
                        new
                        {
                            Id = new Guid("d10c70c8-c0c0-401f-aa58-cb36c7f5a256"),
                            Name = "Гангста-рэп"
                        },
                        new
                        {
                            Id = new Guid("e2319db5-a08c-47c5-9033-00a1c086fca2"),
                            Name = "Готик-рок"
                        },
                        new
                        {
                            Id = new Guid("9dd7e004-1d84-425b-8108-4e44c51e2f0c"),
                            Name = "Гранж"
                        },
                        new
                        {
                            Id = new Guid("a99ed714-c09f-4a6e-a097-7752d8544a0a"),
                            Name = "Дарк-эмбиент"
                        },
                        new
                        {
                            Id = new Guid("b65b84f4-d43c-4a9a-b8c4-4fa4fc80e361"),
                            Name = "Джаз"
                        },
                        new
                        {
                            Id = new Guid("bd692739-f147-4838-86d4-5dac6c5434da"),
                            Name = "Джаз-рэп"
                        },
                        new
                        {
                            Id = new Guid("27be86de-805a-4d35-9d6a-89230e076869"),
                            Name = "Драм-н-бэйс"
                        },
                        new
                        {
                            Id = new Guid("5f4ce11a-a071-4a35-bff4-10985ebb4a3b"),
                            Name = "Дубстеп"
                        },
                        new
                        {
                            Id = new Guid("d979f535-f46a-4c90-b731-d665c00c74b7"),
                            Name = "Дум-метал"
                        },
                        new
                        {
                            Id = new Guid("8dfa2863-9d23-4cbd-b692-e9fca360d3f4"),
                            Name = "Дэт-метал"
                        },
                        new
                        {
                            Id = new Guid("1d4f99b2-5165-4741-9177-ddaddd3a3ed9"),
                            Name = "Дип-хаус"
                        },
                        new
                        {
                            Id = new Guid("0f1838c9-548b-4bcf-ad1b-d87b9770c03a"),
                            Name = "Диско"
                        },
                        new
                        {
                            Id = new Guid("df43ae79-3b05-46db-b611-77e4bbc7763b"),
                            Name = "Диксиленд"
                        },
                        new
                        {
                            Id = new Guid("391456b1-3807-4d68-a744-31b2d489f6cc"),
                            Name = "Дрилл"
                        },
                        new
                        {
                            Id = new Guid("399cd0cc-de05-4664-ad9f-f3ca17b7f549"),
                            Name = "Индie-рок"
                        },
                        new
                        {
                            Id = new Guid("d7d432be-0110-487b-b9c6-db86bc6a8d48"),
                            Name = "Кантри"
                        },
                        new
                        {
                            Id = new Guid("2df59016-82e4-49a2-b91a-4486a70b5684"),
                            Name = "Классическая музыка"
                        },
                        new
                        {
                            Id = new Guid("a785727b-f20d-49ef-b8a3-3de004dd71e0"),
                            Name = "Латино"
                        },
                        new
                        {
                            Id = new Guid("f27247d3-864a-47b6-b986-4eeb15898edc"),
                            Name = "Лоу-фай"
                        },
                        new
                        {
                            Id = new Guid("ec20b847-f556-4ef4-80ef-8edc0df8be2e"),
                            Name = "Метал"
                        },
                        new
                        {
                            Id = new Guid("9fee064d-041e-40c8-ae28-6bf4252debea"),
                            Name = "Металкор"
                        },
                        new
                        {
                            Id = new Guid("a017b28d-4044-40e1-a708-4ab9cba8e182"),
                            Name = "Нью-вейв"
                        },
                        new
                        {
                            Id = new Guid("c3587d6e-37a0-4984-8d84-011e59882588"),
                            Name = "Ню-метал"
                        },
                        new
                        {
                            Id = new Guid("a39b2367-400c-46bb-91c5-f9ba4285927b"),
                            Name = "Панк-рок"
                        },
                        new
                        {
                            Id = new Guid("6750e71b-dec4-4494-aee3-b2ee5d0d7a59"),
                            Name = "Пауэр-метал"
                        },
                        new
                        {
                            Id = new Guid("3f955fd0-c5af-4153-b86c-2c384b33163f"),
                            Name = "Поп-музыка"
                        },
                        new
                        {
                            Id = new Guid("07b8bb61-386c-425e-8496-85dd58d653ef"),
                            Name = "Пост-панк"
                        },
                        new
                        {
                            Id = new Guid("eafac7da-7e73-4000-9253-011daf0d246a"),
                            Name = "Прогрессив-хаус"
                        },
                        new
                        {
                            Id = new Guid("fb07e109-0d38-4feb-889b-6133ac20219b"),
                            Name = "R&B"
                        },
                        new
                        {
                            Id = new Guid("88b0cab6-6983-45d7-8e09-23b91b035d1e"),
                            Name = "Регги"
                        },
                        new
                        {
                            Id = new Guid("4751bb51-b803-4819-8bb4-458085f77742"),
                            Name = "Рок"
                        },
                        new
                        {
                            Id = new Guid("183ab4a5-aefd-4725-9a40-f3b266a64a1f"),
                            Name = "Русский рок"
                        },
                        new
                        {
                            Id = new Guid("02bb7d51-8284-4af9-a7dd-006beb21c8a1"),
                            Name = "Саундтреки"
                        },
                        new
                        {
                            Id = new Guid("88c6ca3d-76cd-43f6-8982-dfa5d708677c"),
                            Name = "Свинг"
                        },
                        new
                        {
                            Id = new Guid("5f70961b-49c3-4570-9604-ac47ba0395cd"),
                            Name = "Симфоник-метал"
                        },
                        new
                        {
                            Id = new Guid("06ab95f9-a482-4dd9-a149-086443feb8e0"),
                            Name = "Синтипоп"
                        },
                        new
                        {
                            Id = new Guid("08c747f0-1411-4917-bda3-51c2f0780385"),
                            Name = "Ска"
                        },
                        new
                        {
                            Id = new Guid("1ac35dd4-782a-4621-9eab-f50a8534637c"),
                            Name = "Соул"
                        },
                        new
                        {
                            Id = new Guid("58927cf6-b95c-4d64-a9ff-ff11e101d63f"),
                            Name = "Техно"
                        },
                        new
                        {
                            Id = new Guid("dbf26d58-c773-4511-82fa-b144d0f01a97"),
                            Name = "Транс"
                        },
                        new
                        {
                            Id = new Guid("adff33bc-f61a-4d89-ada2-eca1fe68bf52"),
                            Name = "Трэп"
                        },
                        new
                        {
                            Id = new Guid("7379c832-2b23-49c3-9ad2-d08b32fc78c9"),
                            Name = "Трэш-метал"
                        },
                        new
                        {
                            Id = new Guid("5bd4a0ce-d963-472a-a916-90941977a424"),
                            Name = "Фанк"
                        },
                        new
                        {
                            Id = new Guid("8be47170-7bd6-4aef-ac82-00146c6d94a2"),
                            Name = "Фолк"
                        },
                        new
                        {
                            Id = new Guid("8503b304-a3ec-4ff2-b7e7-a61e7b8b1cbb"),
                            Name = "Хард-рок"
                        },
                        new
                        {
                            Id = new Guid("202d6de5-9d81-4d49-a917-6420066a9304"),
                            Name = "Хардкор-рэп"
                        },
                        new
                        {
                            Id = new Guid("e318470f-24fc-447a-ac30-787766769013"),
                            Name = "Хаус"
                        },
                        new
                        {
                            Id = new Guid("98ff54bb-672b-44f8-80ff-bf5515f8d2c8"),
                            Name = "Хви-метал"
                        },
                        new
                        {
                            Id = new Guid("3412b477-8f20-465e-82e7-7443bb9f473e"),
                            Name = "Хип-хоп"
                        },
                        new
                        {
                            Id = new Guid("56b16776-2a2a-4f9f-b491-3b5a0383aa9d"),
                            Name = "Хэви-метал"
                        },
                        new
                        {
                            Id = new Guid("2676182d-4e78-4d00-9f87-3cb15a9f309c"),
                            Name = "Шансон"
                        },
                        new
                        {
                            Id = new Guid("924ab745-5ac3-408e-ac4c-d1a4245db9e4"),
                            Name = "Электронная музыка"
                        },
                        new
                        {
                            Id = new Guid("d50b6aa2-38a7-4af2-af3b-844583d32055"),
                            Name = "Эмбиент"
                        },
                        new
                        {
                            Id = new Guid("1f85bb27-e221-47e1-a9a7-161f6c4e738f"),
                            Name = "Эмо"
                        },
                        new
                        {
                            Id = new Guid("aa2b80af-21f0-4796-bfcb-33a9bb206d1f"),
                            Name = "Эстрада"
                        });
                });

            modelBuilder.Entity("Music.Domain.Entities.ThumbnailMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ThumbnailMetadata", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlbumId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ThumbnailId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThumbnailId");

                    b.HasIndex("TrackFileId");

                    b.ToTable("Tracks", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.TrackGenre", b =>
                {
                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid");

                    b.HasKey("TrackId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("TrackGenres", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.TrackMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProcessState")
                        .HasColumnType("integer");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TrackMetadata", "Music");
                });

            modelBuilder.Entity("Music.Domain.Entities.ArtistTrackLink", b =>
                {
                    b.HasOne("Music.Domain.Entities.Artist", "Artist")
                        .WithMany("ArtistTrackLinks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music.Domain.Entities.Track", "Track")
                        .WithMany("ArtistTrackLinks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Music.Domain.Entities.Track", b =>
                {
                    b.HasOne("Music.Domain.Entities.ThumbnailMetadata", "ThumbnailMetadata")
                        .WithMany()
                        .HasForeignKey("ThumbnailId");

                    b.HasOne("Music.Domain.Entities.TrackMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("TrackFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");

                    b.Navigation("ThumbnailMetadata");
                });

            modelBuilder.Entity("Music.Domain.Entities.TrackGenre", b =>
                {
                    b.HasOne("Music.Domain.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Music.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Music.Domain.Entities.Artist", b =>
                {
                    b.Navigation("ArtistTrackLinks");
                });

            modelBuilder.Entity("Music.Domain.Entities.Track", b =>
                {
                    b.Navigation("ArtistTrackLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
